# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-Timestamp
version:      1.01
version_from: lib/Time/Timestamp.pm
installdirs:  site
requires:
    DateTime:                      0.3
    HTTP::Date:                    1.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
